// Generated by scripts/optimize-images.py. Do not edit by hand.
export type PhotoMeta = { w: number; h: number; widths: number[]; alt: string; cat: string | null; color: string };
export const photos = {
  "par-steg": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Ifjú pár a tóparti stégen, a háttérben a nádas és az erdő",
    "cat": "eskuvo",
    "color": "#3f5859"
  },
  "par-asztal": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Menyasszony és vőlegény terített asztalnál a stégen",
    "cat": "eskuvo",
    "color": "#657b69"
  },
  "steg-teritek": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Virágokkal díszített asztal a tó vize fölött, a stégen",
    "cat": "eskuvo",
    "color": "#768d7e"
  },
  "steg-pad": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Zöld pad és csónak a stégen, tükörsima víz",
    "cat": "to",
    "color": "#576550"
  },
  "szertartas-kapu": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fehér virágkapu a gyepen, mögötte a rendezvénypavilon",
    "cat": "eskuvo",
    "color": "#94a37d"
  },
  "szertartas-sorok": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Szertartási virágkapu és fehér székek a park gyepén",
    "cat": "eskuvo",
    "color": "#778c65"
  },
  "szertartas-sorok-2": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fehér masnis székek sorai a szabadtéri szertartáshoz",
    "cat": "eskuvo",
    "color": "#7d9572"
  },
  "szertartas-gyertya": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Gyertyák és fehér rózsák a szertartási asztalon",
    "cat": "eskuvo",
    "color": "#a6b1a8"
  },
  "szertartas-virag": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fehér rózsadísz a szertartási asztalon, mögötte a zöld park",
    "cat": "eskuvo",
    "color": "#a4b793"
  },
  "szertartas-tav": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Szabadtéri szertartás helyszíne a pavilon előtt",
    "cat": "eskuvo",
    "color": "#8c9f73"
  },
  "szertartas-pavilon": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Virágkapu és székek a pavilon mellett",
    "cat": "eskuvo",
    "color": "#819372"
  },
  "asztal-mrmrs": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Főasztal virágfallal és Mr & Mrs felirattal",
    "cat": "eskuvo",
    "color": "#c4c2af"
  },
  "asztal-kerek": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Terített kerek asztal rózsaszín szalagokkal és virágokkal",
    "cat": "eskuvo",
    "color": "#cdc3a7"
  },
  "asztal-reszlet": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Mr & Mrs felirat, gyertyák és fehér rózsák a főasztalon",
    "cat": "eskuvo",
    "color": "#cac6b0"
  },
  "asztal-teritek": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Esküvői teríték pasztell szalagos székekkel",
    "cat": "eskuvo",
    "color": "#cabdae"
  },
  "asztal-tanyer": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fehér tányér és evőeszköz közelről",
    "cat": "eskuvo",
    "color": "#cfc0aa"
  },
  "asztal-hosszu": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Hosszú, fehérre terített asztal virágdísszel",
    "cat": "eskuvo",
    "color": "#bcae91"
  },
  "asztal-141": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Virágfal és díszített asztalok a pavilonban",
    "cat": "eskuvo",
    "color": "#c8c2a5"
  },
  "asztal-142": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fehér virágok és terítékek az ünnepi asztalon",
    "cat": "eskuvo",
    "color": "#bcb79a"
  },
  "asztal-144": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Esküvői asztaldísz fehér virágokkal",
    "cat": "eskuvo",
    "color": "#c9c0a5"
  },
  "asztal-149": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Virágfal előtt a főasztal",
    "cat": "eskuvo",
    "color": "#d4ccad"
  },
  "gyertyas-asztal": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Gyertyafényes teríték virágcsokorral",
    "cat": "eskuvo",
    "color": "#745740"
  },
  "terasz-1": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fonott székek és díszített asztal a tóparti teraszon",
    "cat": "pavilon",
    "color": "#b8bdb6"
  },
  "terasz-2": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Terített asztalok a tóra néző fedett teraszon",
    "cat": "pavilon",
    "color": "#9eaeb0"
  },
  "terasz-3": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fényfüzérek és fonott székek a tóparti teraszon",
    "cat": "pavilon",
    "color": "#9aa7a2"
  },
  "terasz-4": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Hosszú asztal fonott székekkel a teraszon",
    "cat": "pavilon",
    "color": "#aeb7bb"
  },
  "terasz-5": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Asztalsor kilátással a tóra",
    "cat": "pavilon",
    "color": "#acb6b4"
  },
  "terasz-6": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fehér függönyök és terített asztal a teraszon",
    "cat": "pavilon",
    "color": "#b3bcbe"
  },
  "terasz-7": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fonott bútorok a tó fölötti teraszon",
    "cat": "pavilon",
    "color": "#b9c5bb"
  },
  "terasz-8": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A terasz ablakain át a tó és a fák látszanak",
    "cat": "pavilon",
    "color": "#9caba7"
  },
  "terasz-9": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Ünnepi asztal virágokkal a teraszon",
    "cat": "pavilon",
    "color": "#a1a9ad"
  },
  "pavilon-este": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A kivilágított rendezvénypavilon esti fényfüzérekkel",
    "cat": "pavilon",
    "color": "#4e605b"
  },
  "pavilon-este-2": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Fényfüzérek a pavilon és a fák között alkonyatkor",
    "cat": "pavilon",
    "color": "#4e605b"
  },
  "pavilon-alkony": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A pavilon és a gyep alkonyatkor, lámpásokkal",
    "cat": "pavilon",
    "color": "#6b7547"
  },
  "pavilon-ut": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Kivilágított téglaút vezet a pavilonhoz",
    "cat": "pavilon",
    "color": "#515f54"
  },
  "pavilon-nappal": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A zárható oldalfalú rendezvénypavilon nappal",
    "cat": "pavilon",
    "color": "#838d71"
  },
  "pavilon-nappal-2": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A nyolcszögletű pavilon a park fái között",
    "cat": "pavilon",
    "color": "#829669"
  },
  "pavilon-belso": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A pavilon fa tetőszerkezete lámpákkal, belülről",
    "cat": "pavilon",
    "color": "#4f3c2e"
  },
  "pavilon-belso-2": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Fonott székek és hosszú asztalok a pavilonban",
    "cat": "pavilon",
    "color": "#503c29"
  },
  "pavilon-belso-3": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A pavilon belső tere kilátással a parkra",
    "cat": "pavilon",
    "color": "#543e2a"
  },
  "pavilon-este-3": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Esti fények a pavilon körül",
    "cat": "pavilon",
    "color": "#2c3a42"
  },
  "pavilon-gyep": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A pavilon és a nyírt gyep",
    "cat": "pavilon",
    "color": "#768050"
  },
  "pavilon-legi": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Légifotó a pavilonról és a faházakról az erdő közepén",
    "cat": "to",
    "color": "#7a8661"
  },
  "gyertyak": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Gyertyák farönkökben az esti kertben",
    "cat": "pavilon",
    "color": "#3f3129"
  },
  "lugas-este": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Kivilágított fa lugas esti fényben",
    "cat": "park",
    "color": "#674930"
  },
  "lugas-alkony": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fa lugas és a pavilon alkonyatkor",
    "cat": "pavilon",
    "color": "#4e5049"
  },
  "park-este": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Fényfüzérek a park fölött az esti égen",
    "cat": "park",
    "color": "#1d334e"
  },
  "to-legi": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tó és a park légifotón, körülötte az erdő",
    "cat": "to",
    "color": "#899272"
  },
  "to-legi-2": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A kerek tó felülnézetből, a parton a házakkal",
    "cat": "to",
    "color": "#989f79"
  },
  "to-legi-3": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tó felülről, az erdő közepén",
    "cat": "to",
    "color": "#7d8773"
  },
  "to-legi-4": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tó és a fűzfák légifotón",
    "cat": "to",
    "color": "#74796d"
  },
  "to-legi-5": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tópart házai és stégjei légifotón",
    "cat": "to",
    "color": "#7f8270"
  },
  "to-legi-6": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Szomorúfűzek a tó partján, felülről",
    "cat": "to",
    "color": "#757b5b"
  },
  "to-legi-7": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tó és a tóparti épület a fák között",
    "cat": "to",
    "color": "#79766e"
  },
  "to-legi-8": {
    "w": 1200,
    "h": 900,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Az erdő és a tó a magasból",
    "cat": "to",
    "color": "#6e796a"
  },
  "to-1": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A tó és a tóparti lugas napsütésben",
    "cat": "to",
    "color": "#9ea086"
  },
  "to-3": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A tó tükre kék ég alatt",
    "cat": "to",
    "color": "#7b8d85"
  },
  "to-4": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Stég a tó partján",
    "cat": "to",
    "color": "#a1a29a"
  },
  "to-tukor": {
    "w": 1200,
    "h": 674,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tóparti házak tükörképe a vízen",
    "cat": "to",
    "color": "#858376"
  },
  "to-24": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Csendes víztükör, mögötte az erdő",
    "cat": "to",
    "color": "#808a81"
  },
  "to-37": {
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tó és a parti fák",
    "cat": "to",
    "color": "#7d806a"
  },
  "to-fuz": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Fűzfaágak mögött a tó és egy faház",
    "cat": "to",
    "color": "#97af83"
  },
  "tohaz": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A tóparti épület és terasz a víz fölött",
    "cat": "to",
    "color": "#8b9a83"
  },
  "fahaz-to": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Faház a tó partján, tükröződik a vízben",
    "cat": "fahazak",
    "color": "#585b34"
  },
  "fahaz-1": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Fürdőszobás faház fedett terasszal",
    "cat": "fahazak",
    "color": "#897c65"
  },
  "fahaz-terasz": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A faház fedett terasza kerti bútorokkal",
    "cat": "fahazak",
    "color": "#695045"
  },
  "fahaz-konyha": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A faház felszerelt konyhája",
    "cat": "fahazak",
    "color": "#80725d"
  },
  "fahaz-furdo": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Zuhanyzós fürdőszoba a faházban",
    "cat": "fahazak",
    "color": "#909477"
  },
  "fahaz-halo": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A faház hálószobája",
    "cat": "fahazak",
    "color": "#987a60"
  },
  "fahaz-6": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Faház és kemence a parkban",
    "cat": "fahazak",
    "color": "#837454"
  },
  "fahaz-nadas": {
    "w": 750,
    "h": 500,
    "widths": [
      480,
      750
    ],
    "alt": "Négyágyas faház a nádas mellett, a tóparton",
    "cat": "fahazak",
    "color": "#555b37"
  },
  "fahaz-173": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Faház a nagy gyep szélén",
    "cat": "fahazak",
    "color": "#8eac73"
  },
  "fahaz-hal": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Hal alakú tábla a faház falán",
    "cat": "fahazak",
    "color": "#9c6c57"
  },
  "fahaz-177": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Faház virágládákkal",
    "cat": "fahazak",
    "color": "#8b7e72"
  },
  "fahaz-181": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Faház a fák árnyékában",
    "cat": "fahazak",
    "color": "#9d967b"
  },
  "fahaz-to-2": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Faház a tó túlpartján",
    "cat": "fahazak",
    "color": "#7c9881"
  },
  "ponty": {
    "w": 600,
    "h": 450,
    "widths": [
      480,
      600
    ],
    "alt": "Ponty a víz alatt",
    "cat": null,
    "color": "#45543b"
  },
  "amur": {
    "w": 600,
    "h": 450,
    "widths": [
      480,
      600
    ],
    "alt": "Amur a víz alatt",
    "cat": null,
    "color": "#62634a"
  },
  "csuka": {
    "w": 600,
    "h": 450,
    "widths": [
      480,
      600
    ],
    "alt": "Csuka a víz alatt",
    "cat": null,
    "color": "#547766"
  },
  "horgasz-gyerekek": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Gyerekek a stégen horgásznak",
    "cat": "park",
    "color": "#717168"
  },
  "horgasz-botok": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Horgászbotok a tó partján",
    "cat": "to",
    "color": "#838978"
  },
  "horgasz-steg": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Horgászstég a tóparton",
    "cat": "to",
    "color": "#6a7159"
  },
  "hal-tabla": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Hal formájú tábla a tóparton",
    "cat": "park",
    "color": "#73765a"
  },
  "park-jatszo": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Játszótér hintákkal a fák alatt",
    "cat": "park",
    "color": "#545f59"
  },
  "park-kemence": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A kültéri kemence",
    "cat": "park",
    "color": "#5e5548"
  },
  "park-lugas": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Fa lugas a tóparton",
    "cat": "park",
    "color": "#958e79"
  },
  "park-gyep": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A nagy gyep és a park fái",
    "cat": "park",
    "color": "#838e78"
  },
  "park-jatek": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Vendégek játszanak a gyepen",
    "cat": "park",
    "color": "#a3ac89"
  },
  "park-osz": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Ősz a parkban",
    "cat": "park",
    "color": "#757566"
  },
  "park-to-haz": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A tóparti ház és faház",
    "cat": "park",
    "color": "#48573d"
  },
  "park-fahaz-este": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Kivilágított faház este",
    "cat": "park",
    "color": "#574831"
  },
  "park-legi": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A park sportpályái és gyepe felülről",
    "cat": "park",
    "color": "#828b63"
  },
  "park-tel": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Téli hó a parkban",
    "cat": "park",
    "color": "#858893"
  },
  "ajto-hal": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Faragott kapu hal alakú koszorúval",
    "cat": "park",
    "color": "#6b493d"
  },
  "koszoru": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Virágkoszorú hal motívummal",
    "cat": "park",
    "color": "#5d4e45"
  },
  "italok": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Rozé és szódásszifon a tóparton",
    "cat": "park",
    "color": "#838a71"
  },
  "muskatli": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Piros muskátlik",
    "cat": "park",
    "color": "#635952"
  },
  "bisztro": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "A Bisztró terasza fehér székekkel",
    "cat": "park",
    "color": "#807264"
  },
  "bisztro-2": {
    "w": 1200,
    "h": 800,
    "widths": [
      480,
      960,
      1200
    ],
    "alt": "Teraszbútorok a tó mellett",
    "cat": "park",
    "color": "#b4af94"
  },
  "bisztro-3": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "A tóparti Bisztró épülete",
    "cat": "park",
    "color": "#61633d"
  },
  "kut": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Virágos kőkút a pavilon előtt",
    "cat": "park",
    "color": "#767464"
  },
  "erdo-ut": {
    "w": 1080,
    "h": 720,
    "widths": [
      480,
      960,
      1080
    ],
    "alt": "Erdei út a Nyíri erdőben",
    "cat": "park",
    "color": "#6b6045"
  },
  "kapolna": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "A közeli fakápolna télen",
    "cat": "muzeum",
    "color": "#8d95a0"
  },
  "kapolna-2": {
    "w": 960,
    "h": 640,
    "widths": [
      480,
      960
    ],
    "alt": "Faragott oszlop és fa épület a Szent Hubertusz Parkban",
    "cat": "muzeum",
    "color": "#727b61"
  },
  "muzeum": {
    "w": 280,
    "h": 210,
    "widths": [
      280
    ],
    "alt": "Az 1848–49-es relikviák múzeumának belső tere",
    "cat": "muzeum",
    "color": "#7a6254"
  },
  "csalad": {
    "w": 801,
    "h": 549,
    "widths": [
      480,
      801
    ],
    "alt": "Kaluja Szilvia, a Potykató Pihenőpark cégvezetője",
    "cat": null,
    "color": "#959089"
  }
} as const satisfies Record<string, PhotoMeta>;
export type PhotoKey = keyof typeof photos;
